version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: clef_workflow_mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=clef-workflow
      - MYSQL_PASSWORD=clef-workflow
      - MYSQL_DATABASE=clef-workflow
      - MYSQL_ROOT_PASSWORD=clef-workflow

  clef-workflow:
    image: arkitikio/clef-workflow
    container_name: clef_workflow_api
    ports:
      - "9080:9080"
      - "5005:5005"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DATABASE_HOST=clef_workflow_mysql_db
      - DATABASE_PORT=3306
      - DATABASE_NAME=clef-workflow
      - DATABASE_USER=clef-workflow
      - DATABASE_PASSWORD=clef-workflow


