version: "3"
services:
  mysql:
    image: mysql:5.6
    container_name: clef_workflow_mysql_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=clef-workflow
      - MYSQL_PASSWORD=clef-workflow
      - MYSQL_DATABASE=clef-workflow
      - MYSQL_ROOT_PASSWORD=clef-workflow

  clef-workflow:
    image: queeio/clef-workflow
    container_name: clef_workflow_api
    ports:
      - 9080:9080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://clef_workflow_mysql_db/clef-workflow?createDatabaseIfNotExist=true&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=clef-workflow
      - SPRING_DATASOURCE_PASSWORD=clef-workflow


