server:
  port: 9080
spring:
  datasource:
    url: jdbc:h2:file:./clef-workflow-api/clef-workflow-api-deployment/clef-workflow-api-deployment-app/target/h2_db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        storage_engine: innodb
        enable_lazy_load_no_trans: true
  banner:
    image:
      location: banner.txt
  profiles:
    active: h2