server:
  port: 9080
spring:
  datasource:
    url: jdbc:mysql://${database_host:192.168.1.114}:${database_port:3306}/${database_name:clef-workflow}
    username: ${database_user:clef-workflow}
    password: ${database_password:clef-workflow}
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
        enable_lazy_load_no_trans: true
  banner:
    image:
      location: banner.txt
  profiles:
    active: mysql
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false