server:
  port: 9080
spring:
  datasource:
    url: jdbc:mysql://${database_host:localhost}:${database_port:3306}/${database_name:clef-workflow}
    username: ${database_user:clef-workflow}
    password: ${database_password:clef-workflow}
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: io.quee.clef.workflow.api.port.shared.ClefWorkflowNamingStrategy
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
        enable_lazy_load_no_trans: true
  banner:
    image:
      location: banner.txt
  profiles:
    active: mysql
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
arkitik:
  radix:
    logger:
      formatter: json
      logger-name: io.quee.clef.workflow.api.deploy.app.ClefWorkflowApplication
logging:
  level:
    io:
      quee:
        clef: debug