server:
  port: 9080
spring:
  datasource:
    url: jdbc:mysql://192.168.1.114:3306/clef-workflow?createDatabaseIfNotExist=true&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: clef-workflow
    password: clef-workflow
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
        enable_lazy_load_no_trans: true


